import type {ApiFormData} from '@/types'

export const MOCK_DATA: ApiFormData = {
  groups: {
    personal: {
      title: 'Персональные данные',
      blocks: {
        fio: {
          name: {
            type: 'input',
            label: 'Имя',
            placeholder: 'Введите имя',
            value: 'Анна',
            required: 1,
          },
          surname: {
            type: 'input',
            label: 'Фамилия',
            placeholder: 'Введите фамилию',
            value: 'Петрова',
            required: 1,
          },
          lastname: {
            type: 'input',
            label: 'Отчество',
            placeholder: 'Введите отчество',
            value: 'Михайловна',
            required: 0,
          },
          gender: {
            type: 'radio',
            label: 'Пол',
            placeholder: 'Выберите пол',
            value: '2',
            items: ['Не указан', 'Мужской', 'Женский'],
            required: 0,
          },
        },
        birthday: {
          date: {
            type: 'date',
            label: 'Дата рождения',
            placeholder: 'Выберите дату',
            value: '1990-03-15',
            required: 1,
          },
        },
        additional_info: {
          nationality: {
            type: 'select',
            label: 'Национальность',
            placeholder: 'Выберите национальность',
            value: 'russian',
            items: {
              russian: 'Русский',
              kazakh: 'Казах',
              ukrainian: 'Украинец',
              tatar: 'Татарин',
              uzbek: 'Узбек',
              other: 'Другое',
            },
            required: 0,
          },
          marital_status: {
            type: 'radio',
            label: 'Семейное положение',
            placeholder: 'Выберите статус',
            value: '1',
            items: [
              'Не указано',
              'Холост/не замужем',
              'Женат/замужем',
              'Разведен(а)',
              'Вдовец/вдова',
            ],
            required: 0,
          },
        },
      },
    },
    contact: {
      title: 'Контактные данные',
      blocks: {
        main: {
          phone: {
            type: 'input',
            label: 'Телефон',
            placeholder: 'Введите номер телефона',
            value: '+7 (777) 888-99-00',
            required: 1,
          },
          email: {
            type: 'input',
            label: 'Электронная почта',
            placeholder: 'Введите email',
            value: 'anna.petrova@school.kz',
            required: 1,
          },
          address: {
            type: 'input',
            label: 'Адрес',
            placeholder: 'Введите адрес проживания',
            value: 'г. Астана, пр. Нурсултана Назарбаева, д. 42, кв. 15',
            required: 0,
          },
          telegram: {
            type: 'input',
            label: 'Telegram',
            placeholder: 'Введите @username',
            value: '@apetrova_teacher',
            required: 0,
          },
        },
        emergency: {
          emergency_contact: {
            type: 'input',
            label: 'Контакт для экстренной связи',
            placeholder: 'Имя и телефон',
            value: 'Петров Михаил +7 (701) 555-44-33',
            required: 0,
          },
          work_phone: {
            type: 'input',
            label: 'Рабочий телефон',
            placeholder: 'Введите рабочий номер',
            value: '+7 (777) 123-45-67',
            required: 0,
          },
        },
      },
    },
    experience: {
      title: 'Проф. данные',
      blocks: {
        main: [],
      },
      experience: {
        type: 'select',
        label: 'Стаж работы',
        placeholder: 'Выберите стаж работы',
        value: '0',
        items: {
          '0': '0 лет',
          '1': '1 год',
          '2': '2 года',
          '3': '3 года',
          '4': '4 года',
          '5': '5 лет',
          '6': '6 лет',
          '7': '7 лет',
          '8': '8 лет',
          '9': '9 лет',
          '10': '10 лет',
          '11': '11 лет',
          '12': '12 лет',
          '13': '13 лет',
          '14': '14 лет',
          '15': '15+ лет',
        },
        required: 1,
      },
      subjects: {
        type: 'checkboxlist',
        label: 'Предметы',
        placeholder: 'Укажите предметы, которые преподаете',
        value: ['geometry', 'biology', 'english', 'informatics'],
        items: {
          algebra: 'Алгебра',
          geometry: 'Геометрия',
          physics: 'Физика',
          chemistry: 'Химия',
          biology: 'Биология',
          history: 'История',
          geography: 'География',
          literature: 'Литература',
          english: 'Английский язык',
          informatics: 'Информатика',
        },
        required: 1,
      },
      position: {
        type: 'select',
        label: 'Должность',
        placeholder: 'Выберите должность',
        value: 'teacher',
        items: {
          teacher: 'Учитель',
          senior_teacher: 'Старший учитель',
          head_teacher: 'Заведующий кафедрой',
          deputy_director: 'Заместитель директора',
          director: 'Директор',
          psychologist: 'Психолог',
          librarian: 'Библиотекарь',
          coach: 'Тренер',
        },
        required: 1,
      },
    },
    education: {
      title: 'Образование',
      blocks: {
        higher_education: {
          university: {
            type: 'input',
            label: 'ВУЗ',
            placeholder: 'Название университета',
            value: 'КНУ им. аль-Фараби',
            required: 1,
          },
          faculty: {
            type: 'input',
            label: 'Факультет',
            placeholder: 'Название факультета',
            value: 'Физико-технический факультет',
            required: 1,
          },
          specialty: {
            type: 'input',
            label: 'Специальность',
            placeholder: 'Ваша специальность',
            value: 'Физика и информатика',
            required: 1,
          },
          graduation_year: {
            type: 'select',
            label: 'Год окончания',
            placeholder: 'Выберите год',
            value: '2015',
            items: Object.fromEntries(
              Array.from({length: 30}, (_, i) => {
                const year = (2024 - i).toString()
                return [year, year]
              })
            ),
            required: 1,
          },
        },
      },
      degree: {
        type: 'select',
        label: 'Ученая степень',
        placeholder: 'Выберите степень',
        value: 'bachelor',
        items: {
          none: 'Нет',
          bachelor: 'Бакалавр',
          master: 'Магистр',
          phd: 'PhD/Кандидат наук',
          doctor: 'Доктор наук',
        },
        required: 0,
      },
      certifications: {
        type: 'checkboxlist',
        label: 'Сертификаты и курсы',
        placeholder: 'Отметьте пройденные курсы',
        value: ['ict_basic', 'english_b2'],
        items: {
          ict_basic: 'Базовые ИКТ навыки',
          ict_advanced: 'Продвинутые ИКТ навыки',
          english_b1: 'Английский язык B1',
          english_b2: 'Английский язык B2',
          english_c1: 'Английский язык C1',
          pedagogy: 'Курсы педагогики',
          psychology: 'Курсы психологии',
          first_aid: 'Первая медицинская помощь',
          inclusive_education: 'Инклюзивное образование',
          digital_literacy: 'Цифровая грамотность',
        },
        required: 0,
      },
    },
    achievements: {
      title: 'Достижения и награды',
      blocks: {
        awards: {
          best_teacher: {
            type: 'radio',
            label: 'Лучший учитель года',
            placeholder: 'Получали ли награду',
            value: '1',
            items: [
              'Нет',
              'Школьный уровень',
              'Районный уровень',
              'Городской уровень',
              'Республиканский уровень',
            ],
            required: 0,
          },
          publications: {
            type: 'input',
            label: 'Количество публикаций',
            placeholder: 'Введите количество',
            value: '3',
            required: 0,
          },
        },
      },
      languages: {
        type: 'checkboxlist',
        label: 'Владение языками',
        placeholder: 'Отметьте языки, которыми владеете',
        value: ['kazakh', 'russian', 'english'],
        items: {
          kazakh: 'Казахский',
          russian: 'Русский',
          english: 'Английский',
          german: 'Немецкий',
          french: 'Французский',
          chinese: 'Китайский',
          turkish: 'Турецкий',
          arabic: 'Арабский',
        },
        required: 0,
      },
      competitions: {
        type: 'select',
        label: 'Участие в олимпиадах (как руководитель)',
        placeholder: 'Выберите уровень участия',
        value: 'regional',
        items: {
          none: 'Не участвовал',
          school: 'Школьный уровень',
          district: 'Районный уровень',
          regional: 'Областной уровень',
          national: 'Республиканский уровень',
          international: 'Международный уровень',
        },
        required: 0,
      },
    },
    research: [],
  },
}
